/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/notebook/notebook.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Notebook(props) {
  const { nodes, materials } = useGLTF('./models/notebook.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Spiral_Notebook_1.geometry} material={materials.Spiral_Notebook_Cover} />
        <mesh geometry={nodes.Spiral_Notebook_2.geometry} material={materials.Spiral_Notebook_Backboard} />
        <mesh geometry={nodes.Spiral_Notebook_3.geometry} material={materials.Paper} />
        <mesh geometry={nodes.Spiral_Notebook_4.geometry} material={materials.Spiral_Chome} />
        <mesh geometry={nodes.Spiral_Notebook_5.geometry} material={materials.rubberSG} />
      </group>
    </group>
  )
}

export default Notebook;

useGLTF.preload('./models/notebook.gltf');
