/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Product.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Product(props) {
  const { nodes, materials } = useGLTF('./models/Product.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BezierCurve003.geometry} material={materials['Material.002']} position={[-1.93, 1.635, -18.831]} scale={[1.431, 1, 1.884]} />
      <mesh geometry={nodes.PlasticFilm003.geometry} material={materials['Plastic film.001']} position={[2.928, 1.987, -11.832]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Metall} position={[-9.242, 1.128, -18.844]} rotation={[0, -0.305, -Math.PI / 2]} scale={[0.139, 0.682, 0.137]} />
      <mesh geometry={nodes.BackCover001.geometry} material={materials['Material.001']} position={[2.916, 1.259, -11.797]} rotation={[0, 1.571, 0]} scale={[4.938, 1, 7.142]} />
      <mesh geometry={nodes.FrontCover002.geometry} material={materials['Material.001']} position={[2.93, 1.966, -11.83]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.Papers006.geometry} material={nodes.Papers006.material} position={[2.885, 1.279, -11.841]} rotation={[0, 1.571, 0]} scale={[4.938, 1, 7.142]} />
      <mesh geometry={nodes.Spiral.geometry} material={materials.Metall} position={[-3.821, 1.611, -6.609]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.351, 0.25, 0.297]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Metall} position={[7.625, 1.184, -18.747]} rotation={[0, 0.521, -Math.PI / 2]} scale={[0.139, 0.823, 0.212]} />
    </group>
  )
}
export default Product;

useGLTF.preload('/Product.gltf')
