/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.gltf 
Author: Full Barrel Productions (https://sketchfab.com/Full_Barrel_Production)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spiral-notebook-e803910f62cc40d2a2f5668e657fd1cf
Title: Spiral Notebook
*/

import React, { useRef } from 'react'
import { Decal, useGLTF, useTexture, Text } from '@react-three/drei'
import * as THREE from 'three';
import { useModelCustomization } from '../editor/ModelCustomizer';

function Scene(props) {
  const { coverTexture, positionX, positionZ, spiralColor, bandColor, textValue, textColor } = useModelCustomization();
  const { nodes, materials } = useGLTF('./models/scene.gltf');

    // Use a default texture initially
    const defaultTexture = useTexture('./src/assets/moomin-9groke.jpg');

    // If coverTexture is not set, use the default texture
    const currentTexture = coverTexture || defaultTexture;

  //coverTexture.repeat.set(2,2);
  //coverTexture.wrapS = coverTexture.wrapT = THREE.RepeatWrapping;

  return (
    <group {...props} dispose={null}>
      <group scale={2} position={[positionX, -3, positionZ]}>
        <group rotation={[-Math.PI / 1, 0, 0]} scale={25}>
          <mesh geometry={nodes.Spiral_Notebook_Spiral_Notebook_Cover_0.geometry}>
            <meshBasicMaterial transparent opacity={0}/>
            <Decal
            position={[0, -0.03, 0]}
            rotation={[1.57, 0, 0]}
            scale={[0.25, 0.31, 0.1]}
            >
            <Text 
            position={[0, -0.01, 0]} // adjust these values
            rotation={[1.57, 0, 0]} // adjust these values
            scale={[0.01, 0.01, 0.05]} // adjust these values
            >
              {textValue}
              <meshBasicMaterial color={new THREE.Color(textColor)} />
            </Text>  
              <meshBasicMaterial 
                map={currentTexture}
                polygonOffset
                polygonOffsetFactor={1} /> 
            </Decal>
          </mesh>
          <mesh geometry={nodes.Spiral_Notebook_Spiral_Notebook_Backboard_0.geometry} material={materials.Spiral_Notebook_Backboard} />
          <mesh geometry={nodes.Spiral_Notebook_Paper_0.geometry} material={materials.Paper}>
            <meshBasicMaterial color={bandColor.color} />
          </mesh>
          <mesh geometry={nodes.Spiral_Notebook_Spiral_Chome_0.geometry}>
            <meshBasicMaterial color={spiralColor.color} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

{/* /*
        <Decal
          // debug // Makes "bounding box" of the decal visible
          position={pos} // Position of the decal
          rotation={rotation} // Rotation of the decal (can be a vector or a degree in radians)
          scale={scale} // Scale of the decal
        >
          <meshStandardMaterial
            map={texture}
            toneMapped={false}
            transparent
            polygonOffset
            polygonOffsetFactor={-1} // The mesh should take precedence over the original
          />
        </Decal>
*/}

export default Scene;

useGLTF.preload('./models/scene.gltf');
